# -*- coding: utf-8 -*-
"""Formatação da Base IA.ipynb

Automatically generated by Colab.

Original file is located at
    [link do notebook removido]
"""

!pip install google-api-python-client google-auth google-auth-oauthlib -q

import re
from google.colab import auth
from googleapiclient.discovery import build

auth.authenticate_user()

docs_service = build('docs', 'v1')

"""# =========================
# 1. INFORME SEU TEXTO AQUI
# =========================
"""

texto =r"""
8 - CONTINGÊNCIAS
8.1 -  Como Enviar As Contingências
8.1.1 - Para enviar contingencia,  acesse utilitarios > Nfce > Contingencia. Basta clicar na opção ENVIAR. LEMBRANDO,  venda sem status nao fica em contingência. Requer intervenção do suporte.
8.2 - Motivo Da Venda Gerar Contingência Ou Ficar Em Contingência
8.2.1 - As vendas (notas) ficam em estado de contingência por vários motivos, sendo os mais comuns: Sefaz do estado inoperante impossibilitando comunicação. Produtos com dados cadastrais inválidos, como código de barras, Codigo NCM, Codigo Cest, Registro MS, Data de fabricação e/ou vencimento do lote com formato invalido ou vencido. Dados do cadastro do cliente identificado na venda, como Número da residência, Cidade ou Cep inválidos.
8.3 -  Erros Possíveis Ao Enviar Contingências
8.3.1 - Sendo erros mais tecnicos, como total dos pagamentos, erro de troco, total da NF difere do somatório dos itens, entre outros, é necessario contato ao suporte técnico para verificar.
8.3.2-ERRO 12002 - TIME OUT (PROBLEMA REFERENTE À CONEXÃO)
8.3.2.1-Pode ser na sefaz ou no estabelecimento.  Você pode aguardar e tentar o envio das vendas depois.
8.3.3-ERRO 12186 - FALHA NA VALIDAÇÃO DA CHAVE DO CERTIFICADO
8.3.3.1-Problema ocorre quando o certificado não está comunicando  com a máquina, se for o certificado A3 o procedimento é desconectar e conectar o dispositivo. Reiniciar a máquina nesse caso pode ajudar. Sendo o certificado A1 reinstalado e o problema persistindo, pode ser a falta da atualização do Windows 7 ‘kb2992611.
8.3.4-ERRO DE TROCO. Isso ocorre devido a venda ter ficado com um valor superior. O suporte deverá realizar uma análise.
8.3.5-ERRO REJEIÇÃO GTIN CEAN INVÁLIDO
8.3.5.1-Erro no código de barras,  é necessário conferir o código de barras do  produto.  Se mesmo assim o erro persistir consultar o cadastro do mesmo com a distribuidora ou pesquisar na  internet.
8.3.6-ERRO NÃO SERÁ PERMITIDO O CANCELAMENTO DE NFCE COM MAIS DE 30 MIN
8.3.6.1-Verificar o horário do computador do caixa e do servidor e se estiver correto não precisa mudar, mas caso ao contrário é necessário realizar a alteração do horário para não acontecer o erro. Pois o que pode dar problema é que na hora de realizar a autorização da venda a máquina do computador está com o horário errado.
8.3.7-ERRO REJEIÇÃO I.E NÃO CADASTRADA
8.3.7.1 -  É a mesma coisa que inscrição estadual, verificar se a mesma está correta. O acesso para verificação tem que ser feito no servidor, UTILITÁRIOS -> CONFIGURAR -> USUÁRIO.
8.3.8.- ERRO EMISSOR NÃO HABILITADO
8.3.8.1-Erro no CSC, pedir a contabilidade para verificar se existe alguma pendência com a sefaz.
8.3.9.-ERRO NFC-e DE ENTREGA A DOMICILIO SEM A IDENTIFICAÇÃO DO DESTINATÁRIO.
8.3.9.1-Não é possível cancelar uma venda ou nota (nfce) ,que está em contingência (INCONTIGENCIA,CONTINENCIA,COTIGENCIA)
8.3.9.2-Só é possível realizar o cancelamento de uma venda (nota nfce), caso ela não esteja em contingência. Se a venda estiver em contingência ( status =T) Faça o envio e apos
8.3.9.3 - Realize o cancelamento.
8.3.9.4 - Para vendas em delivery, com erro no cadastro, você pode acessar o auxílio contingências e ir na opção tele entrega e fazer as correções.
8.4-Observações:
8.4.1 - As vendas ficam em estado de contingência, ou geram contingencias  por vários motivos, sendo os mais comuns: Sefaz do estado inoperante impossibilitando comunicação. Produtos com dados cadastrais inválidos, como código de barras, Codigo NCM, Codigo Cest, Registro MS, Data de fabricação e/ou vencimento do lote com formato invalido ou vencido. Dados do cadastro do cliente identificado na venda, como Número da residência, Cidade ou Cep inválidos. Mas esse tipo se situação, deve ser acionado o suporte técnico para verificar.
8.4.2-Para enviar todas as contingências, seria ao marcar todas,  e para marcar todas, basta clicar com o botão direito sobre o  mouse em cima do CheckBox de marcação, e selecionar a opção MARCAR TODAS.
8.4.2- Vendas sem status não ficam em contingência, requer intervenção do suporte.
8.5 -  Perguntas esperadas e resposta (base FAQ)

8.5.1 - Pergunta: Como alterar valores de uma venda em contingência?
8.5.1.1 - Resposta:Não é possível alterar os valores após a venda ter sido finalizada, mesmo que esteja em contingência.
8.5.2 - É obrigatório conferir todos os valores antes de finalizar a venda

"""

"""# =========================
# 2. REGRAS DE IDENTIFICAÇÃO
# =========================
"""

regex_topico = re.compile(r'^\d+\s-\s.+$')
regex_subtopico = re.compile(r'^\d+(?:\.\d+)+\s-\s.+$')


# identifica o topico e subtopico
def eh_topico(linha):
    linha_limpa = linha.strip()
    return bool(regex_topico.match(linha_limpa))
def eh_subtopico(linha):
    linha_limpa = linha.strip()
    return bool(regex_subtopico.match(linha_limpa))

#obtem os niveis do subtopico
def obter_nivel_subtopico(texto):
    parte_numerica = texto.split(' - ')[0].strip()
    return parte_numerica.count('.')

#Quebras de Blocos
def quebrar_blocos_numerados(texto):

    # Normaliza travessões somente para ajudar na quebra
    texto = texto.replace("–", "-").replace("—", "-")

    # Quebra quando encontrar uma nova numeração no meio da linha
    # Ex: texto... 51.3.2 - Ao buscar...
    texto = re.sub(
        r'\s+(?=\d+(?:\.\d+){2,}\s*-?\s+)',
        '\n',
        texto
    )

    # Depois garante " - " após a numeração
    texto = re.sub(
        r'^(\d+(?:\.\d+){2,})\s*-?\s+',
        r'\1 - ',
        texto,
        flags=re.MULTILINE
    )

    return texto

#Calcuar as Tabulações
def calcular_tabs(texto):
    numeracao = texto.split(' - ')[0].strip()
    nivel = numeracao.count(".")

    return max(0, (nivel - 1) * 36)

#Correçãp da Palavra Assunto
def corrigir_rotulos(texto):
    texto = re.sub(
        r'\s*ASSUNTO\s*:\s*',
        ' - ',
        texto,
       flags=re.IGNORECASE
    )

    # Evita múltiplos espaços
    texto = re.sub(r'\s+', ' ', texto)

    return texto.strip()

def eh_linha_bloco(texto):
    return bool(
        re.match(
            r'^\s*BLOCO\s+\d+\b',
            texto,
            flags=re.IGNORECASE
        )
    )
#Coloca todo Titulo em caixa alta
def capitalizar_titulo(texto):
    partes = texto.split(' - ', 1)

    if len(partes) != 2:
        return texto

    numeracao = partes[0].strip()
    descricao = partes[1].strip().title()

    return f"{numeracao} - {descricao}"

def formatar_topico(texto):

    partes = texto.split(' - ', 1)

    if len(partes) != 2:
        return texto.upper()

    numeracao = partes[0].strip()
    descricao = partes[1].strip().upper()

    return f"{numeracao} - {descricao}"

# Aplica caixa alta nas primeiras Letras de cada palavra no Subtopcio
def capitalizar_subtopico(texto):
    partes = texto.split(' - ', 1)

    if len(partes) != 2:
        return texto

    numeracao = partes[0]
    descricao = partes[1]

    descricao = descricao.title()

    return f"{numeracao} - {descricao}"

# Padroniza os hifens
def corrigir_hifens(texto):

    texto = texto.strip()

# Corrige apenas o início da linha
    texto = re.sub(
        r'^(\d+(?:\.\d+)*)\s*[–—-]?\s*(.+)$',
        r'\1 - \2',
        texto
    )

 # Remove duplicações logo após a numeração
    texto = re.sub(
        r'^(\d+(?:\.\d+)*)\s*-\s*[–—-]+\s*',
        r'\1 - ',
        texto
    )

    # Remove espaços duplicados
    texto = re.sub(r'\s+', ' ', texto)

    return texto.strip()

"""# =========================
# 3. PROCESSAR TEXTO
# =========================
"""

texto= quebrar_blocos_numerados(texto)
linhas = texto.strip().splitlines()

texto_final = ""
formatacoes = []

indice_atual = 1  # No Google Docs, o texto começa no índice 1

for linha in linhas:


    linha_limpa = linha.strip()

    if eh_linha_bloco(linha_limpa):
        continue
    linha_limpa = corrigir_hifens(linha_limpa)
    linha_limpa = corrigir_rotulos(linha_limpa)
    linha_limpa = corrigir_hifens(linha_limpa)

    if not linha_limpa:
        continue

    recuo = 0

    if eh_topico(linha_limpa):
        tipo = "topico"
        nivel = 0
        recuo = 0
        #linha_formatada = capitalizar_titulo(linha_limpa)
        linha_formatada = formatar_topico(linha_limpa)

    elif eh_subtopico(linha_limpa):
        nivel = obter_nivel_subtopico(linha_limpa)
        recuo = calcular_tabs(linha_limpa)


        if nivel == 1:
            tipo = "subtopico"
            linha_formatada = capitalizar_subtopico(linha_limpa)
        else:
            tipo = "conteudo"
            linha_formatada = linha_limpa
    else:
        tipo="conteudo"
        nivel = 2
        linha_limpa = linha_limpa.replace('\t', ' ')
        linha_limpa = re.sub(r'\s+', ' ', linha_limpa).strip()
        linha_formatada = "\t" + linha_limpa
        recuo = 36
    inicio = indice_atual
    fim = inicio + len(linha_formatada)

    formatacoes.append({
        "tipo": tipo,
        "inicio": inicio,
        "fim": fim,
        "nivel": nivel,
        "recuo":recuo
    })

    texto_final += linha_formatada + "\n"
    indice_atual = fim + 1
print("Prévia do texto final:")
print(texto_final[:1000])
print("Quantidade de caracteres:", len(texto_final))
if not texto_final.strip():
    raise ValueError("O texto_final está vazio. Verifique se a variável texto foi preenchida corretamente.")

"""# =========================
# 4. CRIAR GOOGLE DOCS
# =========================

"""

documento = docs_service.documents().create(
    body={
        "title": "Texto Formatado para Base n8n"
    }
).execute()

document_id = documento["documentId"]

# Inserir texto no documento
docs_service.documents().batchUpdate(
    documentId=document_id,
    body={
        "requests": [
            {
                "insertText": {
                    "location": {
                        "index": 1
                    },
                    "text": texto_final
                }
            }
        ]
    }
).execute()

"""# =========================
# 5. APLICAR FORMATAÇÃO
# =========================

"""

requests = []

for item in formatacoes:
    tipo = item["tipo"]

    if tipo == "topico":
        tamanho_fonte = 17
        negrito = False

    elif tipo == "subtopico":
        tamanho_fonte = 14
        negrito = False

    else:
        tamanho_fonte = 11
        negrito = False

    requests.append({
        "updateTextStyle": {
            "range": {
                "startIndex": item["inicio"],
                "endIndex": item["fim"]
            },
            "textStyle": {
                "fontSize": {
                    "magnitude": tamanho_fonte,
                    "unit": "PT"
                },

            },
            "fields": "fontSize"
        }
    })
    if tipo == "topico":

        requests.append({
        "updateParagraphStyle": {
            "range": {
                "startIndex": item["inicio"],
                "endIndex": item["fim"] + 1
            },
            "paragraphStyle": {
                "spaceAbove": {
                    "magnitude": 18,
                    "unit": "PT"
                },
                "spaceBelow": {
                    "magnitude": 12,
                    "unit": "PT"
                }
            },
            "fields": "spaceAbove,spaceBelow"
        }
    })

    if tipo == "subtopico":
        requests.append({
            "updateParagraphStyle": {
                "range": {
                    "startIndex": item["inicio"],
                    "endIndex": item["fim"] + 1
                },
                "paragraphStyle": {
                    "spaceAbove": {
                        "magnitude": 12,
                        "unit": "PT"
                    },
                    "spaceBelow": {
                        "magnitude": 8,
                        "unit": "PT"
                    }
                },
                "fields": "spaceAbove,spaceBelow"
            }
        })

    if tipo == "conteudo":
        recuo_conteudo = item.get("recuo", 36)

        requests.append({
        "updateParagraphStyle": {
            "range": {
                "startIndex": item["inicio"],
                "endIndex": item["fim"] + 1
            },
            "paragraphStyle":{
                "indentStart": {
                    "magnitude":recuo_conteudo,
                    "unit":"PT"
                },
                "indentFirstLine":{
                    "magnitude":recuo_conteudo,
                    "unit": "PT"
                 },

                "lineSpacing": 100,
                "spaceAbove": {
                    "magnitude": 0,
                    "unit": "PT"
                },
                "spaceBelow": {
                    "magnitude": 0,
                    "unit": "PT"
                }
            },
            "fields": "indentStart,indentFirstLine,lineSpacing,spaceAbove,spaceBelow"
        }

    })

docs_service.documents().batchUpdate(
    documentId=document_id,
    body={
        "requests": requests
    }
).execute()

print("Documento criado com sucesso!")
print(f"https://docs.google.com/document/d/{document_id}/edit")