# -*- coding: utf-8 -*-
"""Geração dos Indices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6_4kWv19o5D4S3URT-2GwTY7n2Zh6Br
"""

!pip install google-api-python-client google-auth google-auth-oauthlib -q

import re
from google.colab import auth
from googleapiclient.discovery import build

auth.authenticate_user()

docs_service = build('docs', 'v1')

texto = r"""
1 - CONFIGURACOES GERAIS
    1.1 - Como Configurar O Perfil Da Empresa
    1.2 - Como Cadastrar Usuarios E Permissoes
    1.3 - Observacoes Importantes
2 - MODULO FINANCEIRO
    2.1 - Como Lancar Uma Conta A Pagar
    2.2 - Como Lancar Uma Conta A Receber
    2.3 - Como Gerar Relatorio De Fluxo De Caixa
    2.4 - Observacoes
3 - MODULO DE ESTOQUE
    3.1 - Como Cadastrar Um Produto
    3.2 - Como Realizar Um Ajuste De Estoque
    3.3 - Como Gerar Relatorio De Inventario
"""


# =========================
# 2. REGEX
# =========================

regex_topico = re.compile(r'^\d+\s-\s.+$')
regex_subtopico = re.compile(r'^\d+\.\d+\s-\s.+$')

def corrigir_hifens(texto):
    texto = texto.strip()
    texto = texto.replace("–", "-").replace("—", "-").replace("−", "-")

    texto = re.sub(r'^(?:\d+(?:\.\d+)*\s*-\s*){2,}', lambda m: m.group(0).replace(' - ', ' - ', 1), texto)
    texto = re.sub(r'^(\d+(?:\.\d+)*)\s*-\s*-\s*', r'\1 - ', texto)
    texto = re.sub(r'^(\d+(?:\.\d+)*)\s+(?!-)(.+)$', r'\1 - \2', texto)
    texto = re.sub(r'^(\d+(?:\.\d+)*)\s*-\s*(.+)$', r'\1 - \2', texto)
    texto = re.sub(r'\s+', ' ', texto)

    return texto.strip()


def eh_topico(linha):
    return bool(regex_topico.match(linha.strip()))

def eh_subtopico(linha):
    return bool(regex_subtopico.match(linha.strip()))


def formatar_topico(texto):
    partes = texto.split(' - ', 1)
    if len(partes) == 2:
        return f"{partes[0].strip()} - {partes[1].strip().upper()}"
    else:
        return texto.upper()


def capitalizar_subtopico(texto):
    partes = texto.split(' - ', 1)

    if len(partes) != 2:
        return texto

    numeracao = partes[0].strip()
    descricao = partes[1].strip().title()

    # Remove pontuação final antiga
    descricao = descricao.rstrip(" .;:!?").strip()

    # Adiciona ponto final
    descricao += "."

    return f"{numeracao} - {descricao}"

def listar_subtopicos_grandes(texto, limite=100):

    resultado = []

    for linha in texto.splitlines():

        linha = linha.strip()

        if not eh_subtopico(linha):
            continue

        partes = linha.split(' - ', 1)

        if len(partes) != 2:
            continue

        descricao = partes[1].strip()

        if len(descricao) > limite:
            resultado.append(linha)

    return resultado

# =========================
# 4. GERAR ÍNDICE
# =========================

linhas = texto.strip().splitlines()

texto_final = ""
formatacoes = []
indice_atual = 1

for linha in linhas:
    linha_limpa = linha.strip()

    if not linha_limpa:
        continue

    linha_limpa = corrigir_hifens(linha_limpa)

    if eh_topico(linha_limpa):
        tipo = "topico"
        linha_formatada = formatar_topico(linha_limpa)

    elif eh_subtopico(linha_limpa):
        tipo = "subtopico"
        linha_formatada = capitalizar_subtopico(linha_limpa)

    else:
        continue

    inicio = indice_atual
    fim = inicio + len(linha_formatada)

    formatacoes.append({
        "tipo": tipo,
        "inicio": inicio,
        "fim": fim
    })

    texto_final += linha_formatada + "\n"
    indice_atual = fim + 1

if not texto_final.strip():
    raise ValueError("Nenhum tópico ou subtópico foi identificado no texto.")

subtopicos_grandes = listar_subtopicos_grandes(texto, 100)
print("\n".join(subtopicos_grandes))

# =========================
# 5. EXIBIR ÍNDICE
# =========================

indice_final = "\n".join(indice)

print(texto_final)

documento = docs_service.documents().create(
    body={
        "title": "iNDICES"
    }
).execute()

document_id = documento["documentId"]

# Inserir texto no documento
docs_service.documents().batchUpdate(
    documentId=document_id,
    body={
        "requests": [
            {
                "insertText": {
                    "location": {
                        "index": 1
                    },
                    "text": texto_final
                }
            }
        ]
    }
).execute()

# =========================
# 5. FORMATAR GOOGLE DOCS
# =========================

requests = []

for item in formatacoes:

    tipo = item["tipo"]

    if tipo == "topico":
        tamanho_fonte = 17
        espaco_acima = 18
        espaco_abaixo = 10

    else:  # subtopico
        tamanho_fonte = 14
        espaco_acima = 4
        espaco_abaixo = 4

    # Fonte
    requests.append({
        "updateTextStyle": {
            "range": {
                "startIndex": item["inicio"],
                "endIndex": item["fim"]
            },
            "textStyle": {
                "fontSize": {
                    "magnitude": tamanho_fonte,
                    "unit": "PT"
                }
            },
            "fields": "fontSize"
        }
    })

    # Sem recuo
    requests.append({
        "updateParagraphStyle": {
            "range": {
                "startIndex": item["inicio"],
                "endIndex": item["fim"] + 1
            },
            "paragraphStyle": {
                "indentStart": {
                    "magnitude": 0,
                    "unit": "PT"
                },
                "indentFirstLine": {
                    "magnitude": 0,
                    "unit": "PT"
                },
                "spaceAbove": {
                    "magnitude": espaco_acima,
                    "unit": "PT"
                },
                "spaceBelow": {
                    "magnitude": espaco_abaixo,
                    "unit": "PT"
                }
            },
            "fields": "indentStart,indentFirstLine,spaceAbove,spaceBelow"
        }
    })

for item in formatacoes:
    print(item)

docs_service.documents().batchUpdate(
    documentId=document_id,
    body={
        "requests": requests
    }
).execute()

print("Documento criado com sucesso!")
print(f"https://docs.google.com/document/d/{document_id}/edit")