# -*- coding: utf-8 -*-
"""Migrando para json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVy9oti4bduRs3dABUuWt8cDCVYyIyNX
"""

import re
from google.colab import files
import json

# =========================
# 1. TEXTO DE ENTRADA
# =========================

texto = r"""
1 - CONFIGURACOES GERAIS
1.1 - Como Configurar O Perfil Da Empresa
1.1.1 - Acesse o menu Configuracoes e clique em Perfil da Empresa.
1.1.2 - Preencha os dados cadastrais e clique em Salvar.
1.2 - Como Cadastrar Usuarios E Permissoes
1.2.1 - Acesse o menu Usuarios e clique em Novo Usuario.
1.2.2 - Defina o nivel de permissao adequado para o usuario.
2 - MODULO FINANCEIRO
2.1 - Como Lancar Uma Conta A Pagar
2.1.1 - Acesse o menu Financeiro e Contas a Pagar.
2.1.2 - Preencha fornecedor, valor e data de vencimento.
2.2 - Como Gerar Relatorio De Fluxo De Caixa
2.2.1 - Acesse Relatorios e selecione Fluxo de Caixa.
"""


# =========================
# 2. REGEX
# =========================

regex_topico = re.compile(r'^\d+\s-\s.+$')
regex_subtopico = re.compile(r'^\d+\.\d+\s-\s.+$')
regex_conteudo = re.compile(r'^\d+(?:\.\d+){2,}\s-\s.+$')

def corrigir_hifens(texto):
    texto = texto.strip()

    texto = texto.replace("–", "-")
    texto = texto.replace("—", "-")
    texto = texto.replace("−", "-")

    texto = re.sub(r'^(\d+(?:\.\d+)*)\s*-\s*-\s*', r'\1 - ', texto)
    texto = re.sub(r'^(\d+(?:\.\d+)*)\s+(?!-)(.+)$', r'\1 - \2', texto)
    texto = re.sub(r'^(\d+(?:\.\d+)*)\s*-\s*(.+)$', r'\1 - \2', texto)

    texto = re.sub(r'\s+', ' ', texto)

    return texto.strip()


def eh_topico(linha):
    return bool(regex_topico.match(linha.strip()))


def eh_subtopico(linha):
    return bool(regex_subtopico.match(linha.strip()))


def eh_conteudo(linha):
    return bool(regex_conteudo.match(linha.strip()))


def extrair_codigo(linha):
    return linha.split(" - ", 1)[0].strip()


def extrair_titulo(linha):
    partes = linha.split(" - ", 1)

    if len(partes) != 2:
        return linha.strip()

    return partes[1].strip()


def formatar_titulo_topico(linha):
    return extrair_titulo(linha).upper()


def formatar_titulo_subtopico(linha):
    return extrair_titulo(linha).title()


def limpar_conteudo(linha):
    linha = linha.strip()
    linha = re.sub(r'^\d+(?:\.\d+)+\s-\s', '', linha)
    linha = re.sub(r'\s+', ' ', linha)
    return linha.strip()


def exportar_json(dados, nome_arquivo="base_conhecimento_agrupada.json", baixar=True):
    with open(nome_arquivo, "w", encoding="utf-8") as f:
        json.dump(dados, f, ensure_ascii=False, indent=4)

    print(f"JSON salvo: {nome_arquivo}")
    print(f"Tópicos: {len(dados)}")

    total_subtopicos = sum(len(topico["subtopicos"]) for topico in dados)
    print(f"Subtópicos: {total_subtopicos}")

    if baixar:
        files.download(nome_arquivo)

# =========================
# 3. GERAR ESTRUTURA
# =========================

base_agrupada = []

topico_atual = None
subtopico_atual = None
contador_topico = 1


for linha in texto.strip().splitlines():

    linha = linha.strip()

    if not linha:
        continue

    linha = corrigir_hifens(linha)

    if eh_topico(linha):

        topico_atual = {
            "id": contador_topico,
            "codigo": extrair_codigo(linha),
            "titulo": formatar_titulo_topico(linha),
            "subtopicos": []
        }

        base_agrupada.append(topico_atual)

        contador_topico += 1

        contador_subtopico = 1

        subtopico_atual = None

    elif eh_subtopico(linha):

        if topico_atual is None:
            continue

        subtopico_atual = {
            "id": contador_subtopico,
            "codigo": extrair_codigo(linha),
            "titulo": formatar_titulo_subtopico(linha),
            "palavras_chave": [],
            "resumo": "",
            "conteudo": []
        }

        topico_atual["subtopicos"].append(subtopico_atual)

        contador_subtopico += 1

    else:

        if subtopico_atual is not None:
            subtopico_atual["conteudo"].append(limpar_conteudo(linha))

# =========================
# 4. SALVAR JSON
# =========================

print(json.dumps(base_agrupada[:1], ensure_ascii=False, indent=4))

exportar_json(
    base_agrupada,
    "base_conhecimento_agrupada.json"
)

print(f"Total de tópicos: {len(base_agrupada)}")

total_subtopicos = sum(
    len(topico["subtopicos"])
    for topico in base_agrupada
)

print(f"Total de subtópicos: {total_subtopicos}")

for topico in base_agrupada[:81]:
    print(topico["titulo"])
    print(f"Subtópicos: {len(topico['subtopicos'])}")
    print()