# -*- coding: utf-8 -*-
"""Conteudos_extensos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsrqL9Gymhn-lp47fLZSqyIIcr0OSI5G
"""

!pip install reportlab -q

import re
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from google.colab import files

# =========================
# 1. TEXTO DE ENTRADA
# =========================

texto = r"""
1 - CONFIGURACOES GERAIS
1.1 - Como Configurar O Perfil Da Empresa
1.1.1 - Acesse o menu Configuracoes e clique em Perfil da Empresa. Preencha nome fantasia, CNPJ, endereco completo e dados de contato. Verifique se todos os campos obrigatorios foram preenchidos antes de salvar, pois o sistema nao permite avancar caso falte alguma informacao essencial para a emissao de documentos fiscais.
1.2 - Como Cadastrar Usuarios E Permissoes
1.2.1 - Acesse o menu Usuarios e clique em Novo Usuario. Defina o nivel de permissao adequado, podendo ser administrador, operador ou consulta. Recomenda-se revisar periodicamente as permissoes concedidas para evitar acessos indevidos a informacoes sensiveis do sistema.
2 - MODULO FINANCEIRO
2.1 - Como Lancar Uma Conta A Pagar
2.1.1 - Acesse o menu Financeiro e Contas a Pagar. Preencha fornecedor, valor, data de vencimento e categoria da despesa. E possivel anexar o comprovante ou nota fiscal referente ao lancamento para consulta futura.
"""


# =========================
# 2. REGEX
# =========================

regex_topico = re.compile(r'^\d+\s-\s.+$')
regex_subtopico = re.compile(r'^\d+\.\d+\s-\s.+$')
regex_conteudo_numerado = re.compile(r'^\d+(?:\.\d+){2,}\s-\s.+$')

# =========================
# 3. FUNÇÕES DE IDENTIFICAÇÃO
# =========================

def corrigir_hifens(texto):
    texto = texto.strip()

    texto = texto.replace("–", "-")
    texto = texto.replace("—", "-")
    texto = texto.replace("−", "-")

    texto = re.sub(r'^(\d+(?:\.\d+)*)\s*-\s*-\s*', r'\1 - ', texto)
    texto = re.sub(r'^(\d+(?:\.\d+)*)\s+(?!-)(.+)$', r'\1 - \2', texto)
    texto = re.sub(r'^(\d+(?:\.\d+)*)\s*-\s*(.+)$', r'\1 - \2', texto)

    texto = re.sub(r'\s+', ' ', texto)

    return texto.strip()


def eh_topico(linha):
    return bool(regex_topico.match(linha.strip()))


def eh_subtopico(linha):
    return bool(regex_subtopico.match(linha.strip()))


def eh_conteudo_numerado(linha):
    return bool(regex_conteudo_numerado.match(linha.strip()))


def extrair_codigo(linha):
    return linha.split(" - ", 1)[0].strip()


def extrair_titulo(linha):
    partes = linha.split(" - ", 1)

    if len(partes) != 2:
        return linha.strip()

    return partes[1].strip()

# =========================
# 4. FUNÇÃO PRINCIPAL
# =========================

def identificar_conteudos_extensos(
    texto,
    limite_caracteres=2500,
    limite_linhas=25,
    limite_palavras=350
):

    relatorio = []

    topico_atual = None
    subtopico_atual = None
    conteudo_atual = []

    def fechar_subtopico():
        if not subtopico_atual:
            return

        texto_conteudo = "\n".join(conteudo_atual).strip()

        qtd_caracteres = len(texto_conteudo)
        qtd_linhas = len(conteudo_atual)
        qtd_palavras = len(texto_conteudo.split())

        if (
            qtd_caracteres > limite_caracteres
            or qtd_linhas > limite_linhas
            or qtd_palavras > limite_palavras
        ):
            relatorio.append({
                "topico": topico_atual,
                "codigo": extrair_codigo(subtopico_atual),
                "subtopico": subtopico_atual,
                "caracteres": qtd_caracteres,
                "linhas": qtd_linhas,
                "palavras": qtd_palavras,
                "preview": texto_conteudo[:500]
            })

    for linha in texto.strip().splitlines():
        linha = corrigir_hifens(linha.strip())

        if not linha:
            continue

        if eh_topico(linha):
            fechar_subtopico()

            topico_atual = linha
            subtopico_atual = None
            conteudo_atual = []

        elif eh_subtopico(linha):
            fechar_subtopico()

            subtopico_atual = linha
            conteudo_atual = []

        else:
            if subtopico_atual is not None:
                conteudo_atual.append(linha)

    fechar_subtopico()

    return relatorio

# =========================
# 5. EXECUTAR ANÁLISE
# =========================

conteudos_extensos = identificar_conteudos_extensos(
    texto,
    limite_caracteres=3000,
    limite_linhas=35,
    limite_palavras=600
)

print(f"Total de conteúdos extensos encontrados: {len(conteudos_extensos)}\n")

for item in conteudos_extensos:
    print("=" * 120)
    print(f"Tópico: {item['topico']}")
    print(f"Código: {item['codigo']}")
    print(f"Subtópico: {item['subtopico']}")
    print(f"Caracteres: {item['caracteres']}")
    print(f"Linhas: {item['linhas']}")
    print(f"Palavras: {item['palavras']}")
    print("\nPrévia:")
    print(item["preview"])
    print()

def gerar_relatorio_pdf_conteudos_extensos(
    relatorio,
    nome_arquivo="relatorio_conteudos_extensos.pdf"
):
    doc = SimpleDocTemplate(
        nome_arquivo,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()

    titulo_style = ParagraphStyle(
        "Titulo",
        parent=styles["Title"],
        fontSize=18,
        spaceAfter=18
    )

    subtitulo_style = ParagraphStyle(
        "Subtitulo",
        parent=styles["Heading2"],
        fontSize=13,
        spaceBefore=12,
        spaceAfter=8
    )

    texto_style = ParagraphStyle(
        "Texto",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        spaceAfter=8
    )

    story = []

    story.append(Paragraph("Relatório de Conteúdos Extensos", titulo_style))
    story.append(Paragraph(f"Total encontrado: {len(relatorio)}", texto_style))
    story.append(Spacer(1, 12))

    if not relatorio:
        story.append(Paragraph("Nenhum conteúdo extenso foi encontrado.", texto_style))

    for  item in relatorio:
        story.append(Paragraph(f"{item['topico']}<br/>{item['subtopico']}", subtitulo_style))

        story.append(Paragraph(f"<b>Tópico:</b> {item['topico']}", texto_style))
        story.append(Paragraph(f"<b>Caracteres:</b> {item['caracteres']}", texto_style))
        story.append(Paragraph(f"<b>Linhas:</b> {item['linhas']}", texto_style))
        story.append(Paragraph(f"<b>Palavras:</b> {item['palavras']}", texto_style))

        preview = item["preview"].replace("\n", "<br/>")
        story.append(Paragraph(f"<b>Prévia:</b><br/>{preview}", texto_style))

        story.append(Spacer(1, 10))


        story.append(PageBreak())

    doc.build(story)

    print(f"PDF gerado com sucesso: {nome_arquivo}")
    files.download(nome_arquivo)

gerar_relatorio_pdf_conteudos_extensos(
    conteudos_extensos,
    "relatorio_conteudos_extensos.pdf"
)